modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
#issueTrackerURL=""

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL = ""
logoFile = "icon.png"
authors = "${mod_author}" #optional
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_range_lower},${minecraft_version_range_upper})"
ordering = "NONE"
side = "BOTH"
